// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "ic-indexer-service/models"

// IcecreamDeleteHandler is an autogenerated mock type for the IcecreamDeleteHandler type
type IcecreamDeleteHandler struct {
	mock.Mock
}

// IcecreamDelete provides a mock function with given fields: _a0
func (_m *IcecreamDeleteHandler) IcecreamDelete(_a0 models.IcecreamClientRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.IcecreamClientRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
